"""Add UserMemory table

Revision ID: 084e6528230c
Revises: 44f8fb6de1dd
Create Date: 2026-08-10 19:33:14.134355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '084e6528230c'
down_revision: Union[str, Sequence[str], None] = '44f8fb6de1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermemory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fact', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usermemory_user_id'), 'usermemory', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usermemory_user_id'), table_name='usermemory')
    op.drop_table('usermemory')
    # ### end Alembic commands ###
