"""Initial migration

Revision ID: afccb75b75ca
Revises: 
Create Date: 2026-08-08 23:55:14.880235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'afccb75b75ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('financialbehaviorprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('salary_cycle_day', sa.Integer(), nullable=False),
    sa.Column('avg_discretionary_spend', sa.Float(), nullable=False),
    sa.Column('repayment_adherence_score', sa.Float(), nullable=False),
    sa.Column('risk_tolerance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issuing_bank', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('minimum_payment', sa.Float(), nullable=False),
    sa.Column('purchase_apr', sa.Float(), nullable=False),
    sa.Column('cash_advance_apr', sa.Float(), nullable=False),
    sa.Column('purchase_balance', sa.Float(), nullable=False),
    sa.Column('cash_advance_balance', sa.Float(), nullable=False),
    sa.Column('raw_source_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depositrecommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('recommended_at', sa.DateTime(), nullable=False),
    sa.Column('schedule_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('projected_interest', sa.Float(), nullable=False),
    sa.Column('baseline_interest', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('depositrecommendation')
    op.drop_table('statement')
    op.drop_table('financialbehaviorprofile')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
